# Generated by Django 4.1.6 on 2023-04-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charakter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pile', models.CharField(blank=True, max_length=150, null=True)),
                ('pile_height', models.IntegerField(blank=True, null=True)),
                ('yarn_weight', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_basic', models.CharField(blank=True, max_length=150, null=True)),
                ('secondary_basic', models.CharField(blank=True, max_length=150, null=True)),
                ('points', models.CharField(blank=True, max_length=150, null=True)),
                ('total_weight', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='palet',
            name='char',
            field=models.ManyToManyField(blank=True, null=True, to='api.charakter'),
        ),
    ]
