# Generated by Django 4.1.6 on 2023-04-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='pile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='pile_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='points',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='primary_basic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='secondary_basic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='total_weight',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='yarn_weight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ourcustomers',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 15, 50, 23, 351827)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 17)),
        ),
    ]
