# Generated by Django 4.1.6 on 2023-04-20 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_design_pile_remove_design_pile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcustomers',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 11, 28, 37, 792649)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 20)),
        ),
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='app.design'),
        ),
    ]
